spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: czn4313@
    url: jdbc:mysql://127.0.0.1:3306/db_smsservice?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 8081
  servlet:
    context-path: /
