spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: czn4313@
    url: jdbc:mysql://127.0.0.1:3306/blackhole_dev?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis: 
    database: 1
    host: 116.62.244.255
    port: 6379
    password: czn4313@
server:
  port: 8081
  servlet:
    context-path: /api
